image: archlinux:latest

before_script:
  - echo "Server = https://mirrors.tuna.tsinghua.edu.cn/archlinux/\$repo/os/\$arch" > /etc/pacman.d/mirrorlist
  - pacman-key --init
  - pacman-key --populate
  - pacman -Syy --noconfirm
  - pacman -S qt5-base gcc cmake ninja python --noconfirm
  
build:
  script:
    - mkdir build && cd build
    - cmake .. -G Ninja
    - ninja
    - cd ..
  artifacts:
    paths:
      - build
