image: ubuntu:20.04

before_script:
  - apt install software-properties-common
  - add-apt-repository ppa:beineri/opt-qt-5.15.3-focal
  - apt update
  - apt install -y qt515base
  - . /opt/qt515/bin/qt515-env.sh
  - apt install -y cmake gcc ninja
  
build:
  script:
    - mkdir build && cd build
    - cmake .. -G Ninja
    - ninja
    - cd ../package
    - ./package.sh
  artifacts:
    paths:
      - earth-wallpaper-amd64.deb
