name: Aur
on:
  push:
    paths-ignore:
      - '.gitlab-ci.yml'
      - '*.md'
      - 'LICENSE'

jobs:
  nightly:
    name: Publish nightly to AUR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: change nightly version
        run: |
          sed -i "s/pkgver=.*/pkgver=$(git describe --tags |  sed  's/\([^-]*-g\)/r\1/;s/-/./g')/g" aur/nightly/PKGBUILD
      - name: Upload Release to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v2.4.1
        with:
          pkgname: earth-wallpaper-nightly
          pkgbuild: aur/nightly/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
