name: Aur
on:
  push:
    paths-ignore:
      - '.gitlab-ci.yml'
      - '*.md'
      - 'LICENSE'

jobs:
  AUR:
    #运行平台
    name: Publish to AUR
    runs-on: ubuntu-20.04
    #编译步骤
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: change version
        run: |
          sed -i "s/pkgver=.*/pkgver=$(git describe --tags |  sed  's/\([^-]*-g\)/r\1/;s/-/./g')/g" package/aur/nightly/PKGBUILD
      #6上传AUR
      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.4.1
        with:
          pkgname: earth-wallpaper-nightly
          pkgbuild: package/aur/nightly/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
      #6发布release
      - name: change version
        if: startsWith(github.ref, 'refs/tags')
        run: |
          sed -i "s/pkgver=.*/pkgver=$(git describe --tags |  sed  's/\([^-]*-g\)/r\1/;s/-/./g')/g" package/aur/bin/PKGBUILD
      - name: Upload Release
        if: startsWith(github.ref, 'refs/tags')
        uses: KSXGitHub/github-actions-deploy-aur@v2.4.1
        with:
          pkgname: earth-wallpaper-bin
          pkgbuild: package/aur/bin/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519