name: Linux
on:
  push:
    paths-ignore:
      - '.gitlab-ci.yml'
      - '*.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '.gitlab-ci.yml'
      - '*.md'
      - 'LICENSE'

jobs:
  #Linux编译
  Build-Linux:
    #运行平台
    name: Build on Linux
    runs-on: ubuntu-20.04
    #编译步骤
    steps:
      #1安装Qt
      - name: Install Qt
        run: |
          sudo add-apt-repository ppa:beineri/opt-qt-5.15.3-focal
          sudo apt update
          sudo apt install qt515base
      - name: Install build tool
        run: |
          sudo apt install -y cmake make dpkg
      #2拉取代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      #3编译构建
      - name: Build
        run: |
          mkdir build
          cd build
          sed -i "s/#define VERSION .*/#define VERSION \"$(git describe --tags |  sed  's/\([^-]*-g\)/r\1/;s/-/./g')\"/g" ../src/about.h
          cmake ..
          make
      #4打包
      - name: Package
        run: |
          pwd
          ls
          cd package
          chmod +x package.sh
          ./package.sh
      #5上传artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: earth-wallpaper-deepin-amd64.deb
          path: package/earth-wallpaper-deepin-amd64.deb
          if-no-files-found: error
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: earth-wallpaper-other-amd64.deb
          path: package/earth-wallpaper-other-amd64.deb
          if-no-files-found: error
      #6发布release
      - name: Upload Release
        if: startsWith(github.ref, 'refs/tags')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: /home/runner/work/earth_wallpaper/earth_wallpaper/package/earth-wallpaper-deepin-amd64.deb
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload Release
        if: startsWith(github.ref, 'refs/tags')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: /home/runner/work/earth_wallpaper/earth_wallpaper/package/earth-wallpaper-other-amd64.deb
          tag: ${{ github.ref }}
          overwrite: true
  AUR:
    #运行平台
    name: Publish to AUR
    runs-on: ubuntu-20.04
    #编译步骤
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: change version
        run: |
          sed -i "s/pkgver=.*/pkgver=$(git describe --long 2>/dev/null | sed  's/\([^-]*-g\)/r\1/;s/-/./g')/g" package/PKGBUILD && git describe --long 2>/dev/null || sed -i "s/pkgver=.*/pkgver=r$(git rev-list --count HEAD).$(git rev-parse --short HEAD)/g"  package/PKGBUILD
      #6上传AUR
      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.5
        with:
          pkgname: earth-wallpaper-git
          pkgbuild: package/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519