name: Linux
on:
  push:
    paths-ignore:
      - '.gitlab-ci.yml'
      - '*.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '.gitlab-ci.yml'
      - '*.md'
      - 'LICENSE'

jobs:
  #Linux编译
  Build-Linux:
    #运行平台
    name: Build on Linux
    runs-on: ubuntu-20.04
    #编译步骤
    steps:
      #1安装Qt
      - name: Install Qt
        run: |
          sudo add-apt-repository ppa:beineri/opt-qt-5.15.3-focal
          sudo apt update
          sudo apt install qt515base
          Source /opt/qt515/bin/qt515-env.sh
      - name: Install build tool
        run: |
          sudo apt install -y cmake make dpkg
      #2拉取代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      #3编译构建
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
      #4打包
      - name: Package
        run: |
          pwd
          ls
          cd package
          chmod +x package.sh
          ./package.sh
      #5上传artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: earth-wallpaper-amd64.deb
          path: package/earth-wallpaper-amd64.deb
          if-no-files-found: error
      #6发布release
      - name: Upload Release
        if: startsWith(github.ref, 'refs/tags')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: /home/runner/work/earth_wallpaper/earth_wallpaper/package/earth-wallpaper-amd64.deb
          tag: ${{ github.ref }}
          overwrite: true