name: Pypi
on:
  push:
    paths-ignore:
      - '.gitlab-ci.yml'
      - '*.md'
      - 'LICENSE'

jobs:
  #Linux编译
  Package:
    name: Package
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - name: Install git
        if: startsWith(github.ref, 'refs/tags')
        run: |
          sudo apt update
          sudo apt install -y git
      - name: Checkout
        if: startsWith(github.ref, 'refs/tags')
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Change Version
        if: startsWith(github.ref, 'refs/tags')
        run: |
          sed -i "s/return.*/return \"$(git describe --tags |  sed  's/\([^-]*-g\)/r\1/;s/-/./g')\"/g" earth_wallpaper/about.py
      - name: Publish package
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}